import Foundation
import SwiftData
import SwiftUI
import Testing
@testable import Refrax

// MARK: - CommandLensSuggestion Model Tests

@Suite("CommandLensSuggestion Model", .tags(.commandLensManager))
@MainActor
struct CommandLensSuggestionModelTests {
    @Test("Each suggestion has unique auto-generated UUID")
    func uniqueAutoGeneratedIds() {
        let suggestion1 = CommandLensSuggestion(
            type: .search,
            text: "Query 1",
            description: "Description 1",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        let suggestion2 = CommandLensSuggestion(
            type: .search,
            text: "Query 1",
            description: "Description 1",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        // Each instance gets a unique UUID
        #expect(suggestion1.id != suggestion2.id)
        #expect(suggestion1 != suggestion2)
    }

    @Test("Equality based on id")
    func equalityBasedOnId() {
        let suggestion = CommandLensSuggestion(
            type: .search,
            text: "Query",
            description: "Description",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        // Same instance is equal to itself
        #expect(suggestion == suggestion)
    }

    @Test("Hash based on id")
    func hashBasedOnId() {
        let suggestion = CommandLensSuggestion(
            type: .search,
            text: "Query",
            description: "Desc",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        // Same instance has same hash
        #expect(suggestion.hashValue == suggestion.hashValue)
    }

    @Test("withGroupHeader creates copy with new header")
    func withGroupHeaderCreatesCopy() {
        let original = CommandLensSuggestion(
            type: .search,
            text: "Query",
            description: "Description",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: true,
            keywordAction: "kw",
            url: nil,
        )

        let withHeader = original.withGroupHeader("New Header")

        // Header should be updated
        #expect(withHeader.groupHeader == "New Header")

        // Other properties should be preserved (except id which is new)
        #expect(withHeader.type == original.type)
        #expect(withHeader.text == original.text)
        #expect(withHeader.description == original.description)
        #expect(withHeader.iconName == original.iconName)
        #expect(withHeader.isRemovable == original.isRemovable)
        #expect(withHeader.keywordAction == original.keywordAction)

        // New copy gets a new UUID
        #expect(withHeader.id != original.id)
    }

    @Test("withGroupHeader replaces existing header")
    func withGroupHeaderReplacesExisting() {
        let original = CommandLensSuggestion(
            type: .search,
            text: "Query",
            description: "Description",
            iconName: "magnifyingglass",
            groupHeader: "Old Header",
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        let withHeader = original.withGroupHeader("New Header")

        #expect(withHeader.groupHeader == "New Header")
    }

    @Test("Can be used in Set with unique ids")
    func canBeUsedInSet() {
        let suggestion1 = CommandLensSuggestion(
            type: .search,
            text: "Query 1",
            description: "Desc",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        let suggestion2 = CommandLensSuggestion(
            type: .search,
            text: "Query 2",
            description: "Desc",
            iconName: "magnifyingglass",
            groupHeader: nil,
            isRemovable: false,
            keywordAction: nil,
            url: nil,
        )

        var set: Set<CommandLensSuggestion> = [suggestion1, suggestion2]
        #expect(set.count == 2)

        // Adding same instance again doesn't increase count
        set.insert(suggestion1)
        #expect(set.count == 2)
    }
}

// MARK: - CommandLensSelection Model Tests

@Suite("CommandLensSelection Model", .tags(.commandLensManager))
@MainActor
struct CommandLensSelectionModelTests {
    @Test("none has index -1")
    func noneHasNegativeIndex() {
        let selection = CommandLensSelection.none

        #expect(selection.index == -1)
        #expect(selection.buttonSelection == .none)
    }

    @Test("Equality compares index and buttonSelection")
    func equalityComparesAll() {
        let selection1 = CommandLensSelection(index: 5, buttonSelection: .keyword)
        let selection2 = CommandLensSelection(index: 5, buttonSelection: .keyword)
        let selection3 = CommandLensSelection(index: 5, buttonSelection: .remove)
        let selection4 = CommandLensSelection(index: 3, buttonSelection: .keyword)

        #expect(selection1 == selection2)
        #expect(selection1 != selection3)
        #expect(selection1 != selection4)
    }

    @Test("ButtonSelection has all expected cases")
    func buttonSelectionCases() {
        let none = CommandLensSelection.ButtonSelection.none
        let keyword = CommandLensSelection.ButtonSelection.keyword
        let remove = CommandLensSelection.ButtonSelection.remove
        let switchProvider = CommandLensSelection.ButtonSelection.switchProvider

        // Just verify they exist and are distinct
        #expect(none != keyword)
        #expect(keyword != remove)
        #expect(remove != switchProvider)
    }

    @Test("Default buttonSelection is none")
    func defaultButtonSelectionIsNone() {
        let selection = CommandLensSelection(index: 0)

        #expect(selection.buttonSelection == .none)
    }
}

// MARK: - SuggestionContext Model Tests

@Suite("SuggestionContext Model", .tags(.commandLensManager))
@MainActor
struct SuggestionContextModelTests {
    @Test("isEmptyInput true for empty string")
    func isEmptyInputTrueForEmpty() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isEmptyInput == true)
    }

    @Test("isEmptyInput true for whitespace only")
    func isEmptyInputTrueForWhitespace() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "   \t\n  ",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isEmptyInput == true)
    }

    @Test("isEmptyInput false for non-empty")
    func isEmptyInputFalseForNonEmpty() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "query",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isEmptyInput == false)
    }

    @Test("isDirectURL true for https://")
    func isDirectURLTrueForHttps() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "https://example.com",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isDirectURL == true)
    }

    @Test("isDirectURL true for http://")
    func isDirectURLTrueForHttp() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "http://example.com",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isDirectURL == true)
    }

    @Test("isDirectURL case insensitive")
    func isDirectURLCaseInsensitive() throws {
        let env = try TabManagerTestEnvironment()

        let context1 = SuggestionContext(
            input: "HTTPS://EXAMPLE.COM",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        let context2 = SuggestionContext(
            input: "HtTpS://Example.com",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context1.isDirectURL == true)
        #expect(context2.isDirectURL == true)
    }

    @Test("isDirectURL false for domain without protocol")
    func isDirectURLFalseForDomain() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "example.com",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isDirectURL == false)
    }

    @Test("isDirectURL false for search query")
    func isDirectURLFalseForQuery() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "how to use https",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isDirectURL == false)
    }

    @Test("isDirectURL handles leading whitespace")
    func isDirectURLHandlesWhitespace() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "  https://example.com",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.isDirectURL == true)
    }

    @Test("Preserves input exactly")
    func preservesInput() throws {
        let env = try TabManagerTestEnvironment()
        let input = "  Test Query  "

        let context = SuggestionContext(
            input: input,
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: nil,
        )

        #expect(context.input == input)
    }

    @Test("Preserves currentTabID")
    func preservesCurrentTabID() throws {
        let env = try TabManagerTestEnvironment()
        let tabID = UUID()

        let context = SuggestionContext(
            input: "query",
            settings: env.settings,
            currentTabID: tabID,
            selectedSearchEngine: nil,
        )

        #expect(context.currentTabID == tabID)
    }

    @Test("Preserves selectedSearchEngine")
    func preservesSelectedSearchEngine() throws {
        let env = try TabManagerTestEnvironment()

        let context = SuggestionContext(
            input: "query",
            settings: env.settings,
            currentTabID: nil,
            selectedSearchEngine: SearchEngine.duckDuckGo,
        )

        #expect(context.selectedSearchEngine == SearchEngine.duckDuckGo)
    }
}

// MARK: - SuggestionType Model Tests

@Suite("SuggestionType Model", .tags(.commandLensManager))
@MainActor
struct SuggestionTypeModelTests {
    @Test("search type is hashable")
    func searchTypeHashable() {
        let type1 = SuggestionType.search
        let type2 = SuggestionType.search

        #expect(type1 == type2)
        #expect(type1.hashValue == type2.hashValue)
    }

    @Test("url type is hashable")
    func urlTypeHashable() {
        let type1 = SuggestionType.url
        let type2 = SuggestionType.url

        #expect(type1 == type2)
    }

    @Test("openTab equality includes tabID")
    func openTabEquality() {
        let id1 = UUID()
        let id2 = UUID()

        let type1 = SuggestionType.openTab(tabID: id1)
        let type2 = SuggestionType.openTab(tabID: id1)
        let type3 = SuggestionType.openTab(tabID: id2)

        #expect(type1 == type2)
        #expect(type1 != type3)
    }

    @Test("searchProvider equality includes engine")
    func searchProviderEquality() {
        let type1 = SuggestionType.searchProvider(.google)
        let type2 = SuggestionType.searchProvider(.google)
        let type3 = SuggestionType.searchProvider(.duckDuckGo)

        #expect(type1 == type2)
        #expect(type1 != type3)
    }

    @Test("richEntity equality includes imageUrl")
    func richEntityEquality() throws {
        let url1 = try #require(URL(string: "https://example.com/image1.png"))
        let url2 = try #require(URL(string: "https://example.com/image2.png"))

        let type1 = SuggestionType.richEntity(imageUrl: url1)
        let type2 = SuggestionType.richEntity(imageUrl: url1)
        let type3 = SuggestionType.richEntity(imageUrl: url2)

        #expect(type1 == type2)
        #expect(type1 != type3)
    }

    @Test("recentlyClosed equality includes index")
    func recentlyClosedEquality() {
        let type1 = SuggestionType.recentlyClosed(index: 0)
        let type2 = SuggestionType.recentlyClosed(index: 0)
        let type3 = SuggestionType.recentlyClosed(index: 1)

        #expect(type1 == type2)
        #expect(type1 != type3)
    }

    @Test("Different types are not equal")
    func differentTypesNotEqual() throws {
        let search = SuggestionType.search
        let url = SuggestionType.url
        let openTab = SuggestionType.openTab(tabID: UUID())
        let searchProvider = SuggestionType.searchProvider(.google)
        let richEntity = try SuggestionType.richEntity(imageUrl: #require(URL(string: "https://example.com")))
        let recentlyClosed = SuggestionType.recentlyClosed(index: 0)

        let types: [SuggestionType] = [search, url, openTab, searchProvider, richEntity, recentlyClosed]

        for i in 0 ..< types.count {
            for j in (i + 1) ..< types.count {
                #expect(types[i] != types[j], "Expected \(types[i]) != \(types[j])")
            }
        }
    }

    @Test("Can be used as dictionary key")
    func canBeUsedAsDictionaryKey() {
        var dict: [SuggestionType: String] = [:]

        dict[.search] = "Search"
        dict[.url] = "URL"
        dict[.openTab(tabID: UUID())] = "Open Tab"

        #expect(dict[.search] == "Search")
        #expect(dict[.url] == "URL")
    }
}

// MARK: - CommandLens Provider Regression Tests

/// Tests for CommandLensManager provider functionality that could regress
/// when implementing settings control (3.1), and CommandLens enhancements.
@Suite("CommandLens Provider", .tags(.commandLensManager), .serialized)
@MainActor
struct CommandLensProviderTests {
    // MARK: - Input Text Handling Tests

    @Test("Input text is trimmed for query")
    func inputTextTrimmed() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("  test  ")

        #expect(manager.inputText == "  test  ")
        // The query should be trimmed internally
    }

    @Test("URL input detected correctly")
    func urlInputDetected() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("https://example.com")

        // When input looks like a URL, behavior should differ
        #expect(manager.inputText == "https://example.com")
    }

    @Test("Domain input detected")
    func domainInputDetected() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("example.com")

        #expect(manager.inputText == "example.com")
    }

    // MARK: - Selection Navigation Tests

    @Test("Selection starts at none")
    func selectionStartsAtNone() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        #expect(manager.selection == .none)
        #expect(manager.selection.index == -1)
    }

    @Test("Selection move down increments when suggestions exist")
    func selectionMoveDownIncrements() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        // Trigger input to generate suggestions
        manager.onInputChanged("test")

        // moveSelection does nothing when suggestions is empty
        // (returns early with guard)
        manager.moveSelection(by: 1)

        // If suggestions exist, selection moves to index 0
        // If empty, selection stays at .none (-1)
        if !manager.suggestions.isEmpty {
            #expect(manager.selection.index >= 0)
        } else {
            #expect(manager.selection == .none)
        }
    }

    @Test("Selection wraps when moving up from index 0")
    func selectionWrapsUpFromFirst() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("test")

        // moveSelection wraps using modulo, doesn't go to .none
        // (0 - 1 + n) % n = (n - 1) = last index
        if !manager.suggestions.isEmpty {
            manager.moveSelection(by: 1) // Select first (index 0)
            manager.moveSelection(by: -1) // Wraps to last

            // With modulo wrap, -1 from index 0 goes to last index
            #expect(manager.selection.index == manager.suggestions.count - 1)
        }
    }

    @Test("Selection wraps at bottom")
    func selectionWrapsAtBottom() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("test")

        // Move down many times past the suggestion count
        for _ in 0 ..< 20 {
            manager.moveSelection(by: 1)
        }

        // Selection should be within valid range (wraps with modulo)
        if !manager.suggestions.isEmpty {
            #expect(manager.selection.index >= 0)
            #expect(manager.selection.index < manager.suggestions.count)
        } else {
            #expect(manager.selection == .none)
        }
    }

    // MARK: - Popup Visibility Tests

    @Test("Popup shows on non-empty input")
    func popupShowsOnInput() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        #expect(!manager.isPopupVisible)

        manager.onInputChanged("query")

        #expect(manager.isPopupVisible)
    }

    @Test("Popup hides on empty input")
    func popupHidesOnEmptyInput() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("query")
        #expect(manager.isPopupVisible)

        manager.onInputChanged("")
        #expect(!manager.isPopupVisible)
    }

    @Test("Popup hides on reset")
    func popupHidesOnReset() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("query")
        #expect(manager.isPopupVisible)

        manager.reset()
        #expect(!manager.isPopupVisible)
    }

    // MARK: - Search Engine Tests

    @Test("Default search engine from settings")
    func defaultSearchEngineFromSettings() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        // Current search engine should use default from settings
        let engine = manager.currentSearchEngine

        #expect(engine == .duckDuckGo)
    }

    @Test("Selected search engine overrides default")
    func selectedSearchEngineOverrides() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        // Set a selected engine
        manager.selectedSearchEngine = SearchEngine.duckDuckGo

        #expect(manager.selectedSearchEngine == SearchEngine.duckDuckGo)
        #expect(manager.currentSearchEngine == SearchEngine.duckDuckGo)
    }

    @Test("Search engine badge shows when engine selected")
    func searchEngineBadgeShows() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        #expect(!manager.showSearchEngineBadge)

        manager.selectedSearchEngine = SearchEngine.google

        #expect(manager.showSearchEngineBadge)
    }

    // MARK: - Inline Completion Tests

    @Test("Inline completion starts nil")
    func inlineCompletionStartsNil() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        #expect(manager.inlineCompletion == nil)
        #expect(manager.inlineCompletionRange == nil)
    }

    @Test("Display text returns inline completion when present")
    func displayTextReturnsCompletionWhenPresent() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.inputText = "test"

        // displayText returns inputText when no completion
        #expect(manager.displayText == "test")

        // displayText returns inlineCompletion when present (replaces, doesn't concatenate)
        manager.inlineCompletion = "testing"
        #expect(manager.displayText == "testing")
    }

    // MARK: - Suggestions Tests

    @Test("Suggestions empty initially")
    func suggestionsEmptyInitially() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        #expect(manager.suggestions.isEmpty)
    }

    @Test("Suggestions cleared on empty input")
    func suggestionsClearedOnEmpty() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        manager.onInputChanged("test")
        manager.onInputChanged("")

        #expect(manager.suggestions.isEmpty)
    }

    // MARK: - Loading State Tests

    @Test("Loading state starts false")
    func loadingStartsFalse() throws {
        let env = try TabManagerTestEnvironment()
        let windowState = env.makeWindowState()

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        #expect(!manager.isLoading)
    }
}

// MARK: - CommandLens Empty State Tests

@Suite("CommandLens Empty State", .tags(.commandLensManager), .serialized)
@MainActor
struct CommandLensEmptyStateTests {
    @Test("Empty state has all directions")
    func emptyStateAllDirections() {
        let directions = EmptyStateDirection.allCases

        #expect(directions.contains(.up))
        #expect(directions.contains(.down))
        #expect(directions.contains(.left))
        #expect(directions.contains(.right))
    }
}

// MARK: - CommandLens Commit Tests

@Suite("CommandLens Commit", .tags(.commandLensManager), .serialized)
@MainActor
struct CommandLensCommitTests {
    @Test("Commit clears input")
    func commitClearsInput() throws {
        let env = try TabManagerTestEnvironment()
        let space = env.makeSpace()
        let windowState = env.makeActiveWindowState(with: space)

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        // Create a tab for the manager to work with
        _ = try env.tabManager.createTab(
            url: #require(URL(string: "https://example.com")),
            in: space,
            makeActive: true,
        )

        manager.onInputChanged("https://test.com")

        // Commit should clear and close
        manager.commitSelection()

        #expect(manager.inputText.isEmpty)
        #expect(!manager.isPopupVisible)
    }

    @Test("Commit hides popup")
    func commitHidesPopup() throws {
        let env = try TabManagerTestEnvironment()
        let space = env.makeSpace()
        let windowState = env.makeActiveWindowState(with: space)

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        _ = try env.tabManager.createTab(
            url: #require(URL(string: "https://example.com")),
            in: space,
            makeActive: true,
        )

        manager.onInputChanged("test query")
        #expect(manager.isPopupVisible)

        manager.commitSelection()

        #expect(!manager.isPopupVisible)
    }

    @Test("Commit resets selection")
    func commitResetsSelection() throws {
        let env = try TabManagerTestEnvironment()
        let space = env.makeSpace()
        let windowState = env.makeActiveWindowState(with: space)

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        _ = try env.tabManager.createTab(
            url: #require(URL(string: "https://example.com")),
            in: space,
            makeActive: true,
        )

        manager.onInputChanged("query")
        manager.moveSelection(by: 1) // Select something

        manager.commitSelection()

        #expect(manager.selection == .none)
    }

    @Test("Commit clears inline completion")
    func commitClearsInlineCompletion() throws {
        let env = try TabManagerTestEnvironment()
        let space = env.makeSpace()
        let windowState = env.makeActiveWindowState(with: space)

        let manager = CommandLensManager(
            tabManager: env.tabManager,
            historyManager: env.historyManager,
            windowState: windowState,
            browserSettings: env.settings,
            siteSettingsManager: env.siteSettingsManager,
            downloadManager: env.downloadManager,
            referencePaneManager: env.referencePaneManager,
            agentChatManager: AgentChatManager(settings: env.settings),
            extensionManager: env.extensionManager,
            customSearchEngineManager: env.customSearchEngineManager,
        )

        _ = try env.tabManager.createTab(
            url: #require(URL(string: "https://example.com")),
            in: space,
            makeActive: true,
        )

        manager.onInputChanged("test")
        manager.inlineCompletion = "completion"

        manager.commitSelection()

        #expect(manager.inlineCompletion == nil)
    }
}
